volumes:
  vol:

networks:
  net:

services:
  main:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        - ARG_PYTHON_VERSION=${PYTHON_VERSION}
        - ARG_UV_VERSION=${UV_VERSION}
        - ARG_NODE_VERSION=${NODE_VERSION}
    environment:
      - HOST=0.0.0.0
    ports:
      - "4321"
      - "4200"
    volumes:
      - vol:/workspace
      - ${HOME}/.gitconfig:/tmp/host-gitconfig:ro
      - ${HOME}/.config/gh:/tmp/host-gh-config:ro
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - net
