volumes:
  vol:

networks:
  net:

services:

  main:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ARG_NODE_VERSION=22
    environment:
      - GH_TOKEN
    ports:
      - 4200:4200
      - 4321:4321
    volumes:
      - vol:/workspaces
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - net
